<p>
    <?php if ($this->auth && $this->HasAccess($this->auth->role, 'warehouses', 'areas-edit')): ?>
        <a href="<?php echo $this->baseUrl; ?>/warehouse/warehouses/areas-edit" class="content-load">Dodaj</a>
    <?php endif;
    ; ?>
</p>
<table class="table">
    <tr>
        <th>Kod</th>
        <th>Nazwa</th>
        <th>&nbsp;</th>
    </tr>

<?php foreach ($this->areas as $area) : ?>
        <tr>
            <td><?php echo $this->escape($area->acronym); ?></td>
            <td><?php echo $this->escape($area->name); ?></td>
            <td>
                   <?php if ($this->auth && $this->HasAccess($this->auth->role, 'warehouses', 'areas-edit')): ?>
                    <a href="<?php echo $this->baseUrl; ?>/warehouse/warehouses/areas-edit/id/<?php echo $area->id; ?>" class="content-load">Edytuj</a>
                   <?php endif; ?>
                   <?php if ($this->auth && $this->HasAccess($this->auth->role, 'warehouses', 'areas-delete')): ?>
                    <a href="<?php echo $this->baseUrl; ?>/warehouse/warehouses/areas-delete/id/<?php echo $area->id; ?>" class="content-load">Usuń</a>
                   <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?> 

</table> 