<h2 class="sub-header">Edycja pozycji katalogu</h2>

<?php if ($this->success): ?>
    <div class="alert alert-success"><?php echo $this->success; ?></div> 
    <button type="button" class="btn btn-success">Powrót</button>
<?php else: ?> 

    <?php if ($this->form->getDescription()): ?>
        <div class="alert alert-danger"><?php echo $this->form->getDescription(); ?></div>
    <?php endif; ?>

    <?php
    $this->form->setAction($this->url());
    echo $this->form;
    ;
    ?>

<?php endif; ?> 

<style>
    .input-group-btn {
        float: right;
        width: 25px;
        padding-left: 5px;
    }
</style>