<div class="jumbotron">
    <div class="container">
        <div class="card card-container">
            <?php if ($this->success): ?>
                <div class="alert alert-success"><?php echo $this->success; ?></div> 
            <?php elseif ($this->error): ?>
                <div class="alert alert-danger"><?php echo $this->error; ?></div> 
            <?php else: ?> 
                <!--<div class="form-group input-group">
                    <span class="input-group-addon">
                        @
                    </span>
                    <input class="form-control" placeholder="Email" name="email" type="email" required="">
                </div>
                <button type="submit" class="btn btn-primary btn-block" id="btn-olvidado">
                    Wyślij nowe hasło
                </button>-->

                <?php if ($this->form->getDescription()): ?>
                    <div class="alert alert-danger"><?php echo $this->form->getDescription(); ?></div>
                <?php endif; ?>
                <?php
                //$this->form->setAction($this->url());
                echo $this->form;
                ?>
                <p class="help-block">
                    <a class="text-muted" href="#" id="acceso"><small></small></a>
                </p>
            <?php endif; ?>
        </div><!-- /card-container -->
    </div><!-- /container -->
</div>

<script>
    $(document).ready(function() {
        var options = {};
        options.ui = {
            showPopover: true,
            showErrors: true,
            showVerdictsInsideProgressBar: true,
            errorMessages: {
                wordLength: "Hasło jest zbyt krótkie",
                wordNotEmail: "Hasło nie może zawierać adresu e-mail",
                wordSimilarToUsername: "Hasło nie może zawierać loginu",
                wordTwoCharacterClasses: "Używaj różne klasy znaków",
                wordRepetitions: "Zbyt wiele powtórzeń znaków",
                wordSequences: "Hasło zawiera sekwencje znaków"
            }
        };
        options.rules = {
            activated: {
                wordTwoCharacterClasses: true,
                wordRepetitions: true
            }
        };
        options.common = {
            onKeyUp: function(evt, data) {
                //console.log($(evt.target).val().length, data.score);
                $('[name=score]').val(data.score);
            }
        }
        $('#password').pwstrength(options);
    });
</script>