<div class="jumbotron">
    <div class="container">
        <div class="card card-container">
            <?php if ($this->success): ?>
                <div class="alert alert-success"><?php echo $this->success; ?></div> 
            <?php else: ?> 
                <span class="help-block">
                    Podaj adres e-mail, którego używasz do logowania na konto.
                    <br>
                    Zostanie wysłany mail z nowym hasłem.
                </span>
                <!--<div class="form-group input-group">
                    <span class="input-group-addon">
                        @
                    </span>
                    <input class="form-control" placeholder="Email" name="email" type="email" required="">
                </div>
                <button type="submit" class="btn btn-primary btn-block" id="btn-olvidado">
                    Wyślij nowe hasło
                </button>-->
                <?php
                //$this->form->setAction($this->url());
                echo $this->form;
                ?>
                <p class="help-block">
                    <a class="text-muted" href="#" id="acceso"><small></small></a>
                </p>
            <?php endif; ?>
        </div><!-- /card-container -->
    </div><!-- /container -->
</div>