<div class="row">
    <div class="col-sm-4 col-xl-3">
        <div class="panel panel-tile text-center br-a br-grey">
            <div class="panel-body">
                <h1 class="fs30 mt5 mbn">
                    <?php if ($this->auth->role == 'technician'): ?>
                        <?php
                        if ($stats = $this->services->find('Przypisane', 'status')):
                            echo $stats->quantity;
                        else:
                            echo 0;
                        endif;
                        ?>
                    <?php else: ?>
                        <?php
                        if ($stats = $this->services->find('Nowe', 'status')):
                            echo $stats->quantity;
                        else:
                            echo 0;
                        endif;
                        ?>
                    <?php endif; ?>
                </h1>
                <h6 class="text-system">Nowe zlecenia</h6>
            </div>
            <!--<div class="panel-footer br-t p12">
                <span class="fs11">
                    <i class="fa fa-arrow-up pr5"></i> 3% INCREASE
                    <b>1W AGO</b>
                </span>
            </div>-->
        </div>
    </div>
    <div class="col-sm-4 col-xl-3">
        <div class="panel panel-tile text-center br-a br-grey">
            <div class="panel-body">
                <h1 class="fs30 mt5 mbn">
                    <?php
                    if ($stats = $this->services->find('Zakończone', 'status')):
                        echo $stats->quantity;
                    else:
                        echo 0;
                    endif;
                    ?>
                </h1>
                <h6 class="text-success">Zakończone</h6>
            </div>
            <!--<div class="panel-footer br-t p12">
                <span class="fs11">
                    <i class="fa fa-arrow-up pr5"></i> 2.7% INCREASE
                    <b>1W AGO</b>
                </span>
            </div>-->
        </div>
    </div>
    <?php if ($this->auth->role == 'technician'): ?>
        <div class="col-sm-4 col-xl-3">
            <div class="panel panel-tile text-center br-a br-grey">
                <div class="panel-body">
                    <h1 class="fs30 mt5 mbn">
                        <?php
                        if ($stats = $this->services->find('Zwrócone', 'status')):
                            echo $stats->quantity;
                        else:
                            echo 0;
                        endif;
                        ?>
                    </h1>
                    <h6 class="text-warning">Zwrócone przez koordynatora</h6>
                </div>
                <!--<div class="panel-footer br-t p12">
                    <span class="fs11">
                        <i class="fa fa-arrow-up pr5 text-success"></i> 1% INCREASE
                        <b>1W AGO</b>
                    </span>
                </div>-->
            </div>
        </div>
    <?php endif; ?>
</div>