<div class="row">
    <div class="col-sm-4 col-xl-3">
        <div class="panel panel-tile text-center br-a br-grey">
            <div class="panel-body">
                <h1 class="fs30 mt5 mbn">
                    <?php if ($this->auth->role == 'technician'): ?><?php
                        if ($this->products && $stats = $this->products->find('Wydane technikowi', 'status')):
                            echo $stats->quantity;
                        else:
                            echo 0;
                        endif;
                        ?>
                    <?php else: ?><?php
                        if ($this->products && $stats = $this->products->find('Nowe', 'status')):
                            echo $stats->quantity;
                        else:
                            echo 0;
                        endif;
                        ?>
                    <?php endif; ?>
                </h1>
                <h6 class="text-system">Produkty w koszyku</h6>
            </div>
            <!--<div class="panel-footer br-t p12">
                <span class="fs11">
                    <i class="fa fa-arrow-up pr5"></i> 3% INCREASE
                    <b>1W AGO</b>
                </span>
            </div>-->
        </div>
    </div>
</div>