<h1>An Error Has Occurred</h1>    
<h2><?php echo $this->message ?></h2>

<?php if ('production' != APPLICATION_ENV): ?>

<h3>Exception information:</h3>
<p>
    <b>Message:</b> <?php echo $this->exception->getMessage() ?>
</p>

<h3>Stack trace:</h3>
<pre><?php echo $this->exception->getTraceAsString() ?>
</pre>

<h3>Request Parameters:</h3>
<pre><?php echo var_export($this->request->getParams(), 1) ?>
</pre>
<?php else: ?>
    <?php if ($this->statusCode == 500): ?>    
<p>We're truly sorry, but we cannot complete your request at this    time.</p>    
<p>If it's any consolation, we have scheduled a new appointment    for our development team leader in Torture Chamber #7 to encourage    his colleagues to investigate this incident.</p>    
    <?php else: ?>        
<p>We're truly sorry, but the page you are trying to locate        does not exist.</p>        
<p>Please double check the requested URL or consult your local        Optometrist.</p>    
    <?php endif; ?>
<?php endif ?>