<?php if ($this->products): ?>
    <table class="table-striped table-bordered table-hover table-condensed overflow" style="empty-cells: hide;" cellspacing="0" width="100%">
        <thead>
        <th>Lp</th>
        <th>Produkt</th>
        <th>Nr seryjny</th>
        <th>Ilość</th>
        <th>
            &nbsp;
            <div class="checkbox" style="visibility: hidden;">
                <label>
                    <input type="checkbox" class="check-all" data-elements-id="id">
                </label>
            </div>
        </th>
    </thead>
    <tbody>
    <?php $loop = 0; foreach ($this->products as $product) : $loop++; ?>
        <tr>
            <td><?php echo $loop; ?></td>
            <td><?php echo $this->escape($product->product); ?></td>
            <td><?php echo $this->escape($product->serial); ?></td>
            <td><?php echo $this->escape($product->quantity); ?></td>
            <td>
                <a href="<?php echo $this->baseUrl; ?>/warehouse/orders/product-delete/id/<?php echo $product->id; ?>" data-target=".modal-body" class="popup-load" title="Usuń z koszyka" style="float: right; margin-top: -20px; ">
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
                <div class="checkbox" style="visibility: hidden;">
                    <label>
                        <input type="checkbox" name="id" value="<?php echo $product->id; ?>" checked>
                    </label>
                </div>
            </td>
        </tr>
        <!--<li>
            <a href="#">
                <div>
        <?php echo $this->escape($product->product); ?>,
                    SN: <?php echo $this->escape($product->serial); ?>,
        <?php echo $this->escape($product->quantity); ?>
                </div>
            </a>
            <a href="<?php echo $this->baseUrl; ?>/warehouse/orders/product-delete/id/<?php echo $product->id; ?>" class="remove-from-basket" title="Usuń z koszyka" style="float: right; margin-top: -20px; ">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        </li>
        <li class="divider"></li>-->
    <?php endforeach; ?> 
        <tr>
            <td colspan="100">
                
    <button class="btn btn-primary btn-sm text-center popup-load" href="<?php echo $this->baseUrl; ?>/warehouse/orders/release" data-target=".modal-body" >
        <strong>Wydaj technikowi</strong>
    <button class="btn btn-danger btn-sm text-center popup-load multi" href="<?php echo $this->baseUrl; ?>/warehouse/orders/product-delete" data-target=".modal-body" >
        <strong>Wyczyść koszyk</strong>
            </td>
        </tr>
        </tbody>
    </table>
    <?php else: ?>
        <li><a href="#">
                <div>Brak produktów</div></a></li>
    <?php endif; ?>

    <script>
        $(document).ready(function() {
            $('.chosen-select').chosen({allow_single_deselect: true});
        });
    </script>