<table class="table display" style="empty-cells: hide;" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Technik</th>
            <th>Data</th>
            <th>Status</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <?php foreach ($this->orders as $order) : ?>
        <tr>
            <td><?php echo $this->escape($order->getTechnician()); ?></td>
            <td><?php echo $this->escape($order->dateadd); ?></td>
            <td><?php echo $this->escape($order->getStatus()); ?></td>
            <td>
                <?php if ($this->auth && $this->HasAccess($this->auth->role, 'orders', 'release') && $order->isAssigned()): ?>
                    <a href="<?php echo $this->baseUrl; ?>/warehouse/orders/release/id/<?php echo $order->id; ?>" data-target="#myModal" class="popup-load">
                        <span class="glyphicon glyphicon-share" aria-hidden="true"></span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?> 

</table> 

<?= $this->paginationControl($this->paginator, 'Sliding', 'helpers/pagination.phtml', array('urlParams' => $this->request)); ?>

<script>
    params = <?php echo Zend_Json::encode($this->request); ?>;
</script>