<h2 class="sub-header">Lista wydań</h2>

<div class="panel panel-default">
    <div class="panel-body">
        <form class="form-inline form-load" action="<?php
        echo $this->url(
                array('module' => 'warehouse', 'controller' => 'orders', 'action' => 'products-list'), 'default', true)
        ?>">
            <div class="form-group">
                <select class="form-control chosen-select" name="warehouseid[]" multiple data-placeholder="Wybierz magazyn">
                    <option value="">Wybierz magazyn</option>
                    <?php foreach ($this->warehouses as $warehouse): ?>
                        <option value="<?php echo $warehouse->id; ?>" <?php if (!empty($this->request['warehouseid']) && in_array($warehouse->id, (array) $this->request['warehouseid'])): ?>selected<?php endif; ?>><?php echo $warehouse->name; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <?php if ($this->auth->role != 'technician'): ?>
            <div class="form-group">
                <select class="form-control chosen-select" multiple name="technicianid[]" multiple data-placeholder="Wybierz technika">
                    <option value="">Wybierz technika</option>
                    <?php foreach ($this->technicians as $technician): ?>
                        <option value="<?php echo $technician->id; ?>" <?php if (!empty($this->request['technicianid']) && in_array($technician->id, (array) $this->request['technicianid'])): ?>selected<?php endif; ?>><?php echo $technician; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <?php endif; ?>
            <div class="form-group">
                <input type="text" class="form-control" name="datefrom" id="datefrom" placeholder="Data od" value="<?php if (!empty($this->request['datefrom'])) echo $this->request['datefrom']; ?>">
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="datetill" id="datetill" placeholder="Data do" value="<?php if (!empty($this->request['datetill'])) echo $this->request['datetill']; ?>">
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="product" placeholder="Nazwa" value="<?php if (!empty($this->request['product'])) echo $this->request['product']; ?>">
            </div>
            <div class="form-group">
                <!--<input type="text" class="form-control" name="serial" placeholder="SN" value="<?php if (!empty($this->request['serial'])) echo $this->request['serial']; ?>">-->
                <textarea class="form-control" name="serial" placeholder="SN"><?php if (!empty($this->request['serial'])): $serials = preg_split("/[\s,]+/", $this->request['serial']); echo join(",\r\n", $serials); endif; ?></textarea>
            </div>
            <button type="button" class="btn btn-default search">Szukaj</button>
            <button type="button" class="btn btn-link xls">Zapisz XLS</button>
        </form>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover table-condensed" style="empty-cells: hide;" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>
        <div class="checkbox">
            <label>
                <input type="checkbox" class="check-all">
            </label>
        </div>
        </th>
        <th style="max-width: 75px !important;">Magazyn</th>
        <th style="max-width: 75px !important;">Data dodania</th>
        <?php if ($this->auth->role != 'technician'): ?>
        <th style="max-width: 75px !important;">Technik</th>
        <?php endif; ?>
        <th style="max-width: 75px !important;">Nazwa</th>
        <th style="max-width: 75px !important;">SN</th>
        <th style="max-width: 55px !important;">Ilość wydana</th>
        <th style="max-width: 55px !important;">Data wydania</th>
        <th style="max-width: 55px !important;">ID Klienta</th>
        <th>Klient</th>
        <?php if ($this->auth->role != 'technician'): ?>
        <th>
            <?php if (/* $product->qtyreleased >= 0 && */$this->auth && $this->HasAccess($this->auth->role, 'orders', 'product-return')): ?>
                <a href="<?php echo $this->baseUrl; ?>/warehouse/orders/product-return" data-target=".modal-body" class="popup-load multi" title="Zwrot">
                    <span class="glyphicon glyphicon-retweet" aria-hidden="true"></span>
                </a>
            <?php endif; ?>
        </th>
        <?php endif; ?>
        </tr>
        </thead>
        <?php foreach ($this->products as $product) : ?>
            <tr>
                <td>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="id" value="<?php echo $product->id; ?>">
                        </label>
                    </div>
                </td>
                <td><?php echo $product->warehouse ? $this->escape($product->warehouse) : '&nbsp;'; ?></td>
                <td><?php echo $this->escape($product->dateadd); ?></td>
                <?php if ($this->auth->role != 'technician'): ?>
                <td><?php echo $this->escape($product->technician); ?></td>
                <?php endif; ?>
                <td><?php echo $this->escape($product->product); ?></td>
                <td><?php echo $this->escape($product->serial); ?></td>
                <td><?php echo $this->escape($product->qtyreleased); ?></td>
                <td><?php echo $this->escape($product->releasedate); ?></td>
                <td><?php echo $product->clientnumber ? $this->escape($product->clientnumber) : '&nbsp;'; ?></td>
                <td><?php echo $product->client ? $this->escape($product->client) : '&nbsp;'; ?></td>
                <?php if ($this->auth->role != 'technician'): ?>
                <td>
                    <!--<?php if ($this->auth && $this->HasAccess($this->auth->role, 'orders', 'release') && $product->isNew()): ?>
                            <a href="<?php echo $this->baseUrl; ?>/warehouse/orders/release/id/<?php echo $product->id; ?>" data-target="#myModal" class="popup-load" title="Wydaj">
                                <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                            </a>
                    <?php endif; ?>-->
                    <?php if ($product->qtyavailable > 0 && !$product->client && $this->auth && $this->HasAccess($this->auth->role, 'orders', 'product-return')): ?>
                        <a href="<?php echo $this->baseUrl; ?>/warehouse/orders/product-return/id/<?php echo $product->id; ?>" data-target=".modal-body" class="popup-load" title="Zwrot">
                            <span class="glyphicon glyphicon-retweet" aria-hidden="true"></span>
                        </a>
                    <?php else: echo '&nbsp;'; endif; ?>
                </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?> 
    </table> 
</div>
<?= $this->paginationControl($this->paginator, 'Sliding', 'helpers/pagination.phtml', array('urlParams' => $this->request)); ?>
<script>
    params = <?php echo Zend_Json::encode($this->request); ?>;
    $(document).ready(function() {
        $('[data-toggle="popover"]').popover({
            html: true
        });
        $('[name=warehouseid]').outerWidth(200);
        $('.chosen-select').chosen({allow_single_deselect: true});
        $("#datefrom").datepicker({
            dateFormat: "yy-mm-dd",
        });
        $("#datetill").datepicker({
            dateFormat: "yy-mm-dd",
        });
        <?php if ($this->auth->role == 'technician'): ?>
        columnsDef = [{
                'bSortable': false,
                'aTargets': [0]
            },
            {
                'bSortable': false,
                'aTargets': [8]
            }];
        <?php else: ?>
        columnsDef = [{
                'bSortable': false,
                'aTargets': [0]
            },
            {
                'bSortable': false,
                'aTargets': [10]
            }];
        <?php endif; ?>
    });
</script>
<script src="/js/dataTables.js" />