<?php
$urlParams = isset($this->urlParams) ? $this->urlParams : array();
?>

<?php if ($this->pageCount): ?>
    <div class="paginationControl">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <a href="<?= $this->url(array_merge($urlParams, array('page' => $this->previous))); ?>">
                < Previous
            </a> |
        <?php else: ?>
            <span class="disabled">< Previous</span> |
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?= $this->url(array_merge($urlParams, array('page' => $page))); ?>">
                    <?= $page; ?>
                </a> |
            <?php else: ?>
                <?= $page; ?> |
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <a href="<?= $this->url(array_merge($urlParams, array('page' => $this->next))); ?>">
                Next >
            </a>
        <?php else: ?>
            <span class="disabled">Next ></span>
        <?php endif; ?>
    </div>
<?php endif; ?>