<?php echo $this->doctype() ?>
<html lang="pl">
    <head>
        <meta charset="UTF-8">
        <?php echo $this->headMeta() ?>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>
    </head>

    <body>

        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php
                    echo $this->url(
                            array('controller' => 'index', 'action' => 'index'), 'default', true)
                    ?>">CEZ</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <?php if ($this->auth): ?>
                        <ul class="nav navbar-nav navbar-left">
                            <?php if ($this->auth && $this->HasAccess($this->auth->role, 'services', 'index')): ?>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Zlecenia <span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <?php if ($this->auth && $this->HasAccess($this->auth->role, 'services', 'list')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'services', 'controller' => 'services', 'action' => 'list', 'typeid' => $this->types ? $this->types->find('installation', 'acronym')->id : ''), 'default', true)
                                                ?>" class="content-load">Zlecenia instalacyjne</a></li>
                                               <?php endif; ?>
                                               <!--<?php if ($this->auth && $this->HasAccess($this->auth->role, 'services', 'add')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'services', 'controller' => 'services', 'action' => 'add', 'typeid' => $this->types ? $this->types->find('installation', 'acronym')->id : ''), 'default', true)
                                                ?>" class="content-load">Dodaj zlecenie instalacyjne</a></li>
                                               <?php endif; ?>-->
                                               <?php if ($this->auth && $this->HasAccess($this->auth->role, 'services', 'import')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'services', 'controller' => 'services', 'action' => 'import', 'typeid' => $this->types ? $this->types->find('installation', 'acronym')->id : ''), 'default', true)
                                                ?>" class="content-load">Imortuj zlecenia instalacyjne</a></li>
                                               <?php endif; ?>
                                               <!--<?php if ($this->auth && $this->HasAccess($this->auth->role, 'reports', 'generate')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'services', 'controller' => 'reports', 'action' => 'generate', 'typeid' => $this->types ? $this->types->find('installation', 'acronym')->id : ''), 'default', true)
                                                ?>" class="content-load">Generuj zestawienie</a></li>
                                               <?php endif; ?>-->
                                        <li role="separator" class="divider"></li>
                                        <?php if ($this->auth && $this->HasAccess($this->auth->role, 'services', 'list')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'services', 'controller' => 'services', 'action' => 'list', 'typeid' => $this->types ? $this->types->find('service', 'acronym')->id : ''), 'default', true)
                                                ?>" class="content-load">Zlecenia serwisowe</a></li>
                                               <?php endif; ?>
                                               <!--<?php if ($this->auth && $this->HasAccess($this->auth->role, 'services', 'add')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'services', 'controller' => 'services', 'action' => 'add', 'typeid' => $this->types ? $this->types->find('service', 'acronym')->id : ''), 'default', true)
                                                ?>" class="content-load">Dodaj zlecenie serwisowe</a></li>
                                               <?php endif; ?>-->
                                               <?php if ($this->auth && $this->HasAccess($this->auth->role, 'services', 'import')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'services', 'controller' => 'services', 'action' => 'import', 'typeid' => $this->types ? $this->types->find('service', 'acronym')->id : ''), 'default', true)
                                                ?>" class="content-load">Imortuj zlecenia serwisowe</a></li>
                                               <?php endif; ?>
                                               <?php if ($this->auth && $this->HasAccess($this->auth->role, 'reports', 'generate')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'services', 'controller' => 'reports', 'action' => 'generate', 'typeid' => $this->types ? $this->types->find('service', 'acronym')->id : ''), 'default', true)
                                                ?>" class="content-load">Generuj zestawienie</a></li>
                                               <?php endif; ?>
                                        <li role="separator" class="divider"></li>
                                        <?php if ($this->auth && $this->HasAccess($this->auth->role, 'services', 'search')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'services', 'controller' => 'services', 'action' => 'search'), 'default', true)
                                                ?>" class="content-load">Wyszukaj zlecenie</a></li>
                                               <?php endif; ?>
                                               <?php if ($this->auth && $this->HasAccess($this->auth->role, 'reports', 'list')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'services', 'controller' => 'reports', 'action' => 'list'), 'default', true)
                                                ?>" class="content-load">Zestawienia</a></li>
                                               <?php endif; ?>
                                        <li role="separator" class="divider"></li>
                                        <?php if ($this->auth && $this->HasAccess($this->auth->role, 'services', 'migration')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'services', 'controller' => 'services', 'action' => 'migration'), 'default', true)
                                                ?>" class="content-load">Migracja danych</a></li>
                                               <?php endif; ?>
                                    </ul>
                                </li>
                            <?php endif; ?>
                            <?php if ($this->auth && $this->HasAccess($this->auth->role, 'orders', 'products-list')): ?>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Magazyn <span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <?php if ($this->auth && $this->HasAccess($this->auth->role, 'warehouses', 'list')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'warehouse', 'controller' => 'warehouses', 'action' => 'list'), 'default', true)
                                                ?>" class="content-load">Magazyny</a></li>
                                               <?php endif; ?>
                                               <?php if ($this->auth && $this->HasAccess($this->auth->role, 'warehouses', 'edit')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'warehouse', 'controller' => 'warehouses', 'action' => 'edit'), 'default', true)
                                                ?>" class="content-load">Dodaj</a></li>
                                               <?php endif; ?>
                                        <li role="separator" class="divider"></li>
                                        <?php if ($this->auth && $this->HasAccess($this->auth->role, 'products', 'list')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'warehouse', 'controller' => 'products', 'action' => 'list'), 'default', true)
                                                ?>" class="content-load">Produkty</a></li>
                                               <?php endif; ?>
                                               <?php if ($this->auth && $this->HasAccess($this->auth->role, 'products', 'edit')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'warehouse', 'controller' => 'products', 'action' => 'edit'), 'default', true)
                                                ?>" class="content-load">Dodaj</a></li>
                                               <?php endif; ?>
                                               <?php if ($this->auth && $this->HasAccess($this->auth->role, 'products', 'import')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'warehouse', 'controller' => 'products', 'action' => 'import'), 'default', true)
                                                ?>" class="content-load">Imortuj</a></li>
                                               <?php endif; ?>
                                               <?php if ($this->auth && $this->HasAccess($this->auth->role, 'orders', 'products-list')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'warehouse', 'controller' => 'orders', 'action' => 'products-list', 'released' => 1), 'default', true)
                                                ?>" class="content-load">Wydania</a></li>
                                               <?php endif; ?>
                                        <?php if ($this->auth && $this->HasAccess($this->auth->role, 'products', 'migration')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'warehouse', 'controller' => 'products', 'action' => 'migration'), 'default', true)
                                                ?>" class="content-load">Migracja danych</a></li>
                                               <?php endif; ?>
                                    </ul>
                                </li>
                            <?php endif; ?>
                            <?php if ($this->auth && $this->HasAccess($this->auth->role, 'users', 'list')): ?>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administracja <span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <?php if ($this->auth && $this->HasAccess($this->auth->role, 'users', 'list')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'admin', 'controller' => 'users', 'action' => 'list'), 'default', true)
                                                ?>" class="content-load">Użytkownicy</a></li>
                                               <?php endif; ?>
                                               <?php if ($this->auth && $this->HasAccess($this->auth->role, 'users', 'edit')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'admin', 'controller' => 'users', 'action' => 'edit'), 'default', true)
                                                ?>" class="content-load">Dodaj</a></li>
                                               <?php endif; ?>
                                        <li role="separator" class="divider"></li>
                                        <?php if ($this->auth && $this->HasAccess($this->auth->role, 'dictionaries', 'list')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'admin', 'controller' => 'dictionaries', 'action' => 'list'), 'default', true)
                                                ?>" class="content-load">Słowniki</a></li>
                                               <?php endif; ?>
                                               <?php if ($this->auth && $this->HasAccess($this->auth->role, 'dictionaries', 'edit')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'admin', 'controller' => 'dictionaries', 'action' => 'edit'), 'default', true)
                                                ?>" class="content-load">Dodaj</a></li>
                                               <?php endif; ?>
                                               <?php if ($this->auth && $this->HasAccess($this->auth->role, 'products', 'import')): ?>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('module' => 'admin', 'controller' => 'dictionaries', 'action' => 'import'), 'default', true)
                                                ?>" class="content-load">Imortuj</a></li>
                                               <?php endif; ?>
                                    </ul>
                                </li>
                            <?php endif; ?>
                        </ul>
                        <ul class="nav navbar-top-links navbar-right">
                            <li class="dropdown">
                                <?php if ($this->auth && $this->HasAccess($this->auth->role, 'orders', 'products-check')): ?>
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
                                        <i class="fa fa-shopping-cart fa-fw"></i>  <i class="fa fa-caret-down"></i>
                                    </a>
                                    <ul class="dropdown-menu dropdown-messages" id="basket">

                                    </ul>
                                <?php endif; ?>
                            </li>
                            <li class="dropdown">
                            </li>
                            <!-- /.dropdown -->
                            <li class="dropdown">
                            </li>
                            <!-- /.dropdown -->
                            <li class="dropdown">
                            </li>
                            <!-- /.dropdown -->
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-user"></i> 
                                    <?php echo $this->auth->firstname . ' ' . $this->auth->lastname . ' (' . $this->auth->role . ')'; ?> 
                                    <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="#"><i class="fa fa-fw fa-gear"></i> Ustawienia</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="<?php
                                        echo $this->url(
                                                array('controller' => 'auth', 'action' => 'logout'), 'default', true)
                                        ?>"><i class="fa fa-fw fa-power-off"></i> Wyloguj</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    <?php else: ?>

                    <?php endif; ?>
                </div>
            </div>
        </nav>

        <div class="container-fluid" id="page">
            <div class="row">
                <div id="content" class="col-sm-12 col-sm-offset-0 col-md-12 col-md-offset-0 main">
                    <?php echo $this->layout()->content ?>
                </div>
            </div>
        </div>
        
        <footer class="footer">
      <div class="container">
        <p class="text-muted"><strong>Copyright</strong> Nplay CEZ © <?php echo date('Y'); ?> v. <?php echo $this->version; ?></p>
      </div>
    </footer>

        <!-- Default bootstrap modal example -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <!--<h4 class="modal-title" id="myModalLabel">Modal title</h4>-->
                    </div>
                    <div class="modal-body">
                        ...
                    </div>
                    <!--<div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Save changes</button>
                    </div>-->
                </div>
            </div>
        </div>

        <div id='loading-indicator' style="position: fixed; left: 50%; top: 50%; display: none;">
            <img src="/css/images/ajax-loader.gif" />
        </div>

    </body>
</html>
