<h2 class="sub-header">Lista produktów</h2>

<div class="panel panel-default">
    <div class="panel-body">
        <form class="form-inline form-load" action="<?php
        echo $this->url(
                array('module' => 'warehouse', 'controller' => 'products', 'action' => 'list'), 'default', true)
        ?>">
            <div class="form-group">
                <select class="form-control chosen-select" name="statusid[]" multiple data-placeholder="Wybierz status">
                    <option value="">Wybierz status</option>
                    <?php foreach ($this->statuses as $status): if ($status['acronym'] == 'deleted'): continue; endif; ?>
                        <option value="<?php echo $status->id; ?>" <?php if (!empty($this->request['statusid']) && in_array($status->id, (array)$this->request['statusid'])): ?>selected<?php endif; ?>><?php echo $status->name; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <select class="form-control chosen-select" name="warehouseid[]" multiple data-placeholder="Wybierz magazyn">
                    <option value="">Wybierz magazyn</option>
                    <?php foreach ($this->warehouses as $warehouse): ?>
                        <option value="<?php echo $warehouse->id; ?>" <?php if (!empty($this->request['warehouseid']) && in_array($warehouse->id, (array)$this->request['warehouseid'])): ?>selected<?php endif; ?>><?php echo $warehouse->name; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="name" placeholder="Nazwa" value="<?php if (!empty($this->request['name'])) echo $this->request['name']; ?>">
            </div>
            <div class="form-group">
                <!--<input type="text" class="form-control" name="serial" placeholder="SN" value="<?php if (!empty($this->request['serial'])) echo $this->request['serial']; ?>">-->
                <textarea class="form-control" name="serial" placeholder="SN"><?php if (!empty($this->request['serial'])): $serials = preg_split("/[\s,]+/", $this->request['serial']); echo join(",\r\n", $serials); endif; ?></textarea>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="qtyavailable" placeholder="Ilość dostępna" value="<?php if (!empty($this->request['qtyavailable'])) echo $this->request['qtyavailable']; ?>">
            </div>
            <button type="button" class="btn btn-default search">Szukaj</button>
            <button type="button" class="btn btn-link xls">Zapisz XLS</button>
        </form>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover table-condensed" style="empty-cells: hide;" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th style="max-width: 15px !important;">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" class="check-all">
                        </label>
                    </div>
                </th>
                <th style="max-width: 75px !important;">Magazyn</th>
                <th>Nazwa</th>
                <th style="max-width: 55px !important;">Ilość</th>
                <th style="max-width: 55px !important;">Ilość dostępna</th>
                <!--<th>Ilość zarezerwowana</th>
                <th>Ilość wydana</th>
                <th>Ilość zwrócona</th>-->
                <th style="max-width: 75px !important;">Jednostka</th>
                <th style="max-width: 125px !important;">SN</th>
                <th style="max-width: 75px !important;">Sprzęt sparowany</th>
                <th style="max-width: 75px !important;">Status</th>
                <th style="max-width: 55px !important;">
                    <?php if ($this->auth && $this->HasAccess($this->auth->role, 'orders', 'product-add')): ?>
                        <a href="<?php echo $this->baseUrl; ?>/warehouse/orders/product-add" data-target=".modal-body" class="popup-load multi" title="Dodaj do koszyka">
                            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                        </a>
                    <?php endif; ?>
                    <?php if ($this->auth && $this->HasAccess($this->auth->role, 'orders', 'product-release')): ?>
                        <a href="<?php echo $this->baseUrl; ?>/warehouse/orders/product-add-release" data-target=".modal-body" class="popup-load multi" title="Wydaj technikowi">
                            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                        </a>
                    <?php endif; ?>
                    <?php if ($this->auth && $this->HasAccess($this->auth->role, 'products', 'accept')): ?>
                        <a href="<?php echo $this->baseUrl; ?>/warehouse/products/accept" data-target=".modal-body" class="popup-load multi" title="Potwierdź przyjęcie">
                            <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
                        </a>
                    <?php endif; ?>
                    <?php if ($this->auth && $this->HasAccess($this->auth->role, 'products', 'delete')): ?>
                        <a href="<?php echo $this->baseUrl; ?>/warehouse/products/delete" data-target=".modal-body" class="popup-load multi" title="Usuń">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        </a>
                    <?php endif; ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($this->products as $product) : ?>
            <tr>
                <td>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="id" value="<?php echo $product->id; ?>">
                        </label>
                    </div>
                </td>
                <td><?php echo $product->warehouse ? $this->escape($product->warehouse) : '&nbsp;'; ?></td>
                <td><?php echo $product->name ? $this->escape($product->name) : '&nbsp;'; ?></td>
                <td><?php echo $this->escape($product->quantity); ?></td>
                <td><?php echo $this->escape($product->qtyavailable); ?></td>
                <!--<td><?php echo $this->escape($product->qtyreserved); ?></td>
                <td><?php echo $this->escape($product->qtyreleased); ?></td>
                <td><?php echo $this->escape($product->qtyreturned); ?></td>-->
                <td><?php echo $this->escape($product->unit); ?></td>
                <td><?php echo $product->serial ? $this->escape($product->serial) : '&nbsp;'; ?></td>
                <td><?php echo $product->pairedcard ? $this->escape($product->pairedcard) : '&nbsp;'; ?></td>
                <td><?php echo $this->escape($product->status); ?></td>
                <td>
                    <?php if ($product->qtyreleased): ?>
                    <a href="<?php echo $this->baseUrl; ?>/warehouse/products/details/id/<?php echo $product->id; ?>" data-target=".modal-body" class="popup-load" title="Wydania">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                    </a>
                    <?php endif; ?>
                    <?php if ($this->auth && $this->HasAccess($this->auth->role, 'orders', 'product-add') && $product->isAvailable()): ?>
                        <a href="<?php echo $this->baseUrl; ?>/warehouse/orders/product-add/id/<?php echo $product->id; ?>" data-target=".modal-body" class="popup-load" title="Dodaj do koszyka">
                            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                        </a>
                    <?php endif; ?>
                    <?php if ($this->auth && $this->HasAccess($this->auth->role, 'orders', 'product-release') && $product->isAvailable()): ?>
                        <a href="<?php echo $this->baseUrl; ?>/warehouse/orders/product-add-release/id/<?php echo $product->id; ?>" data-target=".modal-body" class="popup-load" title="Wydaj technikowi">
                            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                        </a>
                    <?php endif; ?>
                    <?php if ($this->auth && !$product->qtyreleased && !$product->qtyreserved && $this->HasAccess($this->auth->role, 'products', 'edit')): ?>
                        <a href="<?php echo $this->baseUrl; ?>/warehouse/products/edit/id/<?php echo $product->id; ?>" class="content-load" title="Edytuj">
                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                        </a>
                    <?php endif; ?>
                    <?php if ($this->auth && $this->HasAccess($this->auth->role, 'products', 'accept') && $product->isNew()): ?>
                        <a href="<?php echo $this->baseUrl; ?>/warehouse/products/accept/id/<?php echo $product->id; ?>" data-target=".modal-body" class="popup-load" title="Potwierdź przyjęcie">
                            <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
                        </a>
                    <?php endif; ?>
                    <?php if ($this->auth &&!$product->qtyreleased && !$product->qtyreserved && $this->HasAccess($this->auth->role, 'products', 'delete')): ?>
                        <a href="<?php echo $this->baseUrl; ?>/warehouse/products/delete/id/<?php echo $product->id; ?>" data-target=".modal-body" class="popup-load" title="Usuń">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?> 
    </table> 
</div>
<?= $this->paginationControl($this->paginator, 'Sliding', 'helpers/pagination.phtml', array('urlParams' => $this->request)); ?>
<script>
    params = <?php echo Zend_Json::encode($this->request); ?>;
    $(document).ready(function() {
        $('[data-toggle="popover"]').popover({
            html: true
        });
        $('[name=warehouseid]').outerWidth(200);
        $('.chosen-select').chosen({allow_single_deselect: true});
        columnsDef = [{
                'bSortable': false,
                'aTargets': [0]
            },
            {
                'bSortable': false,
                'aTargets': [9]
            }];
    });
</script>
<script src="/js/dataTables.js" />

<iframe id="file-download" name="file-download" style="display: none"></iframe>