<h2 class="sub-header">
    <?php if ($this->request['typeid'] == $this->types->find('installation', 'acronym')->id): ?>
        Instalacja
    <?php elseif ($this->request['typeid'] == $this->types->find('service', 'acronym')->id): ?>
        Serwis
    <?php endif; ?>
    - <?php echo $this->service->client; ?>
</h2>

<?php if ($this->success): ?>
    <div class="alert alert-success"><?php echo $this->success; ?></div> 
    <button type="button" class="btn btn-success">Powrót</button>
<?php else: ?> 

    <?php if ($this->form->getDescription()): ?>
        <div class="alert alert-danger"><?php echo $this->form->getDescription(); ?></div>
    <?php endif; ?>

    <?php
    $this->form->setAction($this->url());
    echo $this->form;
    ;
    ?>

<?php endif; ?> 

<script>
    $(function() {
        $('.chosen-select').not('[name^=installationcodeid]').not('[multiple=multiple][name^=productreturnedid]').not('[multiple=multiple][name^=productid]').chosen({
            search_contains: true,
            allow_single_deselect: true,
            placeholder_text_multiple: 'dodaj'
        });
        $('.chosen-select[name^=installationcodeid]').chosen({
            search_contains: true,
            allow_single_deselect: true,
            multiple: false,
            placeholder_text_multiple: 'dodaj',
            max_selected_options: 1
        }).change(function(e) {
            
        });
        onInstallationCodeChange();
        function onInstallationCodeChange() {
            //$(".chosen-select[name^=installationcodeid]").off();
            $(".chosen-select[name^=installationcodeid]").on("change", function(e) {
                if (!e.currentTarget.value) {
                    if ($(".chosen-select[name^=installationcodeid]").size() == 1) {
                        return false;
                    }
                    $(e.currentTarget).next('.chosen-container').remove();
                } else {
                    div = $('[name="installationcodeid[installationcodeid-0][]"]').parents('.form-group.inline').clone();
                    if (div.size()) {
                        length = $('.chosen-select[name^="installationcodeid"]').length;
                        div.find('.chosen-container').remove();
                        div.find('select').show();
                        div.find('select').val([]);
                        div.find('select').attr('name', 'installationcodeid[installationcodeid-' + length + '][]');
                        div.find('select').attr('id', 'installationcodeid-installationcodeid-' + length + '');
                        $(div).insertAfter($($(e.currentTarget).parents('.form-group.inline').last()));
                        $('.chosen-select[name^="installationcodeid[installationcodeid-' + length + ']"]').chosen({
                            search_contains: true,
                            allow_single_deselect: true,
                            multiple: false,
                            placeholder_text_multiple: 'dodaj',
                            max_selected_options: 1
                        });
                        onInstallationCodeChange();
                    }
                }
            });
        };
        $('.chosen-select[multiple=multiple][name^=productreturnedid]').chosen({
            search_contains: true,
            allow_single_deselect: true,
            multiple: false,
            placeholder_text_multiple: 'dodaj',
            max_selected_options: 1,
            display_disabled_options: false
        });
        $('.chosen-select[name^=productreturnedid]').each(function(i, n) {
            $(n).find('option').not(':selected').each(function(k, v) {
                $(v).attr('disabled', 'disabled');
            });
            $(n).trigger('chosen:updated');
        });
        onProductReturnedChange();
        function onProductReturnedChange() {
            //$(".chosen-select[name^=productreturnedid]").off();
            $(".chosen-select[name^=productreturnedid]").on("change", function(e) {
                if (!e.currentTarget.value) {
                    if ($(".chosen-select[name^=productreturnedid]").size() == 1) {
                        return false;
                    }
                    $(e.currentTarget).parents('div.form-group').remove();
                } else {
                    div = $(e.currentTarget).parents('div.form-group').clone();
                    if (div.size()) {
                        tmp = $('.chosen-select[name^="productreturnedid"]').last().attr('name').match(/\d+/);
                        length = parseInt(tmp[0]) + 1;
                        div.find('.chosen-container').remove();
                        div.find('select').show();
                        div.find('select').val([]);
                        div.find('select[name^=catalogid]').attr('name', 'catalogid[catalogid-' + length + ']');
                        div.find('select[name^=catalogid]').attr('id', 'catalogid-catalogid-' + length + '');
                        div.find('select[name^=productreturnedid]').attr('name', 'productreturnedid[productreturnedid-' + length + '][]');
                        div.find('select[name^=productreturnedid]').attr('id', 'productreturnedid-productreturnedid-' + length + '');
                        div.find('select[name^=demagecodeid]').attr('name', 'demagecodeid[demagecodeid-' + length + ']');
                        div.find('select[name^=demagecodeid]').attr('id', 'demagecodeid-demagecodeid-' + length + '');
                        div.find('input').attr('name', 'demaged[demaged-' + length + ']');
                        div.find('input').attr('id', 'demaged-demaged-' + length + '');
                        div.attr('id', 'demaged-' + length + '-label');
                        div.find('label').attr('for', 'demaged-demaged-' + length + '');
                        div.find('select[name^=demagecodeid]').parents('span').show();
                        div.find('select[name^=demagecodeid]').parents('span').prev('span').show();
                        $(div).insertAfter($(e.currentTarget).parents('div.form-group'));
                        $('.chosen-select[name^="productreturnedid[productreturnedid-' + length + ']"]').chosen({
                            search_contains: true,
                            allow_single_deselect: true,
                            multiple: false,
                            placeholder_text_multiple: 'dodaj',
                            max_selected_options: 1,
                            display_disabled_options: false
                        });
                        $('.chosen-select[name^="demagecodeid[demagecodeid-' + length + ']"]').chosen({
                            search_contains: true,
                            allow_single_deselect: true,
                            multiple: false,
                            placeholder_text_multiple: 'wybierz',
                            max_selected_options: 1
                        });
                        $('.chosen-select[name^="catalogid[catalogid-' + length + ']"]').chosen({
                            search_contains: true,
                            allow_single_deselect: true,
                            multiple: false,
                            placeholder_text_multiple: 'wybierz',
                            max_selected_options: 1
                        });
                        onProductReturnedChange();
                    }
                }
            });
            setTimeout(function () {
                $('.chosen-select[name^=catalogid]').on('change', function(event) {
                    products = $('.chosen-select[multiple=multiple][name^=productreturnedid]').not('[name="' + $(this).attr('name') + '"]').map(function(i, n) {
                        return $(n).find('option:selected').val();
                    }).toArray();
                    select = $(this).parents('div.form-group').find('select[name^=productreturnedid]');
                    select.find('option').each(function(i, n) {
                        if ($(this).val() && products.indexOf($(n).val()) === -1)
                            $(n).removeAttr('disabled');
                        else 
                            $(n).attr('disabled', 'disabled');
                    });
                    $(select).trigger("chosen:updated");
                });
            }, 1000);
        };
        $('select[disabled=disabled]').each(function (i, e) {
            $($(e).parents('dd')).append($('<input type="hidden" name="' + e.name + '" value="' + e.value + '">'));
        });
        $('.chosen-select[multiple=multiple][name^=productid]').chosen({
            search_contains: true,
            allow_single_deselect: true,
            multiple: false,
            placeholder_text_multiple: 'dodaj',
            max_selected_options: 1,
            display_disabled_options: false
        });
        $('.chosen-select[name^=productid]').each(function(i, n) {
            $(n).find('option').not(':selected').each(function(k, v) {
                $(v).attr('disabled', 'disabled');
            });
            $(n).trigger('chosen:updated');
        });
        onProductChange();
        function onProductChange() {
            //$(".chosen-select[name^=productid]").off();
            $(".chosen-select[name^=productid]").on("change", function(e) {
                if (!e.currentTarget.value) {
                    if ($(".chosen-select[name^=productid]").size() == 1) {
                        return false;
                    }
                    $(e.currentTarget).parents('div.form-group').remove();
                } else {
                    div = $(e.currentTarget).parents('div.form-group').clone();
                    if (div.size()) {
                        tmp = $('.chosen-select[name^="productid"]').last().attr('name').match(/\d+/);
                        length = parseInt(tmp[0]) + 1;
                        div.find('.chosen-container').remove();
                        div.find('select').show();
                        div.find('select').val([]);
                        div.find('select[name^=productwarehouseid]').attr('name', 'productwarehouseid[productwarehouseid-' + length + '][]');
                        div.find('select[name^=productwarehouseid]').attr('id', 'productwarehouseid-productwarehouseid-' + length + '');
                        div.find('select[name^=productid]').attr('name', 'productid[productid-' + length + '][]');
                        div.find('select[name^=productid]').attr('id', 'productid-productid-' + length + '');
                        div.find('input').attr('name', 'quantity[quantity-' + length + ']');
                        div.find('input').attr('id', 'quantity-quantity-' + length + '');
                        div.find('input').val('');
                        div.find('input').removeAttr('disabled');
                        div.attr('id', 'demaged-' + length + '-label');
                        div.find('label').attr('for', 'quantity-quantity-' + length + '');
                        $(div).insertAfter($(e.currentTarget).parents('div.form-group'));
                        $('.chosen-select[name^="productwarehouseid[productwarehouseid-' + length + ']"]').chosen({
                            search_contains: true,
                            allow_single_deselect: true,
                            multiple: false,
                            placeholder_text_multiple: 'Magazyn',
                            max_selected_options: 1
                        });
                        $('.chosen-select[name^="productid[productid-' + length + ']"]').chosen({
                            search_contains: true,
                            allow_single_deselect: true,
                            multiple: false,
                            placeholder_text_multiple: 'dodaj',
                            max_selected_options: 1,
                            display_disabled_options: false
                        });
                        onProductChange();
                    }
                }
            });
            setTimeout(function () {
                $('.chosen-select[name^=productwarehouseid]').on('change', function(event) {
                    if ($(this).find('option:selected').attr('data-type') == 'EQP') {
                        $(this).parents('div.form-group').find('[name^=quantity]').val('1');
                        $(this).parents('div.form-group').find('[name^=quantity]').attr('disabled', 'disabled');
                    } else {
                        $(this).parents('div.form-group').find('[name^=quantity]').removeAttr('disabled');
                        $(this).parents('div.form-group').find('[name^=quantity]').val('');
                    };
                    products = $('.chosen-select[multiple=multiple][name^=productid]').not('[name="' + $(this).attr('name') + '"]').map(function(i, n) {
                        return $(n).find('option:selected').val();
                    }).toArray();
                    select = $(this).parents('div.form-group').find('select[name^=productid]');
                    warehouseid = $(this).val();
                    select.find('option').each(function(i, n) {
                        if ($(this).val() && $(n).attr('data-warehouseid') == warehouseid && products.indexOf($(n).val()) === -1)
                            $(n).removeAttr('disabled');
                        else 
                            $(n).attr('disabled', 'disabled');
                    });
                    $(select).trigger("chosen:updated");
                });
            }, 1000);
        };

        /*var select, chosen;
         // cache the select element as we'll be using it a few times
         select = $(".chosen-select");
         // init the chosen plugin
         select.chosen();
         // get the chosen object
         chosen = select.data('chosen');
         console.log(select, chosen, chosen.dropdown);
         // Bind the keyup event to the search box input
         chosen.find('input').keyup(function(e)
         {
         // if we hit Enter and the results list is empty (no matches) add the option
         if (e.which == 13 && chosen.find('li.no-results').length > 0)
         {
         var option = $("<option>").val(this.value).text(this.value);
         
         // add the new option
         select.prepend(option);
         // automatically select it
         select.find(option).prop('selected', true);
         // trigger the update
         select.trigger("chosen:updated");
         }
         });*/

<?php if ($this->request['typeid'] == $this->types->find('service', 'acronym')->id): ?>
            $("#datefinished").timepicker({
                timeFormat: 'HH:mm',
                hourGrid: 4,
                minuteGrid: 10,
                stepMinute: 5
            });
            $('#solutioncodeid').on('change', function(e) {
                $('#decoderinterchangecodeid-element').hide();
                $('#decoderinterchangecodeid-label').hide();
                $('#modeminterchangecodeid-element').hide();
                $('#modeminterchangecodeid-label').hide();
                $('[name^=demagecodeid]').first().parents('span.form-group').show();
                $('[name^=demagecodeid]').first().parents('span.form-group').prev().show();
                $('[name^=catalogid]').first().parents('span.form-group').prev().show();
                e.preventDefault();
                var errorCodes = [];
                $.each($(this).find('option:selected'), function(key, value) {
                    errorCodes.push($(value).attr('data-errorcodeid'));
                })
                $('#errorcodeid').val(errorCodes);
                $('#errorcodeid').trigger("chosen:updated");
                if ($(this).find('option:selected').attr('data-solutioncode')) {
                    var tmp = $(this).find('option:selected').attr('data-solutioncode').split('-');
                    switch (tmp[0]) {
                        // dekoder
                        case 'ST1':
                            switch (tmp[1]) {
                                case 'WKW':
                                case 'WKX':
                                    $('#modeminterchangecodeid-element').hide();
                                    $('#modeminterchangecodeid-label').hide();
                                    $('#decoderinterchangecodeid-element').show();
                                    $('#decoderinterchangecodeid-label').show();
                                    $('[name^=demagecodeid]').first().parents('span.form-group').hide();
                                    $('[name^=demagecodeid]').first().parents('span.form-group').prev().hide();
                                    $('[name^=catalogid]').first().parents('span.form-group').prev().hide();
                                    break;
                            }
                            break;
                        case 'SCI':
                            switch (tmp[1]) {
                                case 'WKW':
                                    $('#modeminterchangecodeid-element').hide();
                                    $('#modeminterchangecodeid-label').hide();
                                    $('#decoderinterchangecodeid-element').show();
                                    $('#decoderinterchangecodeid-label').show();
                                    $('[name^=demagecodeid]').first().parents('span.form-group').hide();
                                    $('[name^=demagecodeid]').first().parents('span.form-group').prev().hide();
                                    $('[name^=catalogid]').first().parents('span.form-group').prev().hide();
                                    break;
                            }
                            break;
                            // modem
                        case 'UMD':
                            switch (tmp[1]) {
                                case 'WKW':
                                case 'WKX':
                                    $('#decoderinterchangecodeid-element').hide();
                                    $('#decoderinterchangecodeid-label').hide();
                                    $('#modeminterchangecodeid-element').show();
                                    $('#modeminterchangecodeid-label').show();
                                    $('[name^=demagecodeid]').first().parents('span.form-group').hide();
                                    $('[name^=demagecodeid]').first().parents('span.form-group').prev().hide();
                                    $('[name^=catalogid]').first().parents('span.form-group').prev().hide();
                                    break;
                            }
                            break;
                        case 'WIF':
                            switch (tmp[1]) {
                                case 'WKW':
                                    $('#decoderinterchangecodeid-element').hide();
                                    $('#decoderinterchangecodeid-label').hide();
                                    $('#modeminterchangecodeid-element').show();
                                    $('#modeminterchangecodeid-label').show();
                                    $('[name^=demagecodeid]').first().parents('span.form-group').hide();
                                    $('[name^=demagecodeid]').first().parents('span.form-group').prev().hide();
                                    $('[name^=catalogid]').first().parents('span.form-group').prev().hide();
                                    break;
                            }
                            break;
                        case 'SIP':
                            switch (tmp[1]) {
                                case 'WKW':
                                    $('#decoderinterchangecodeid-element').hide();
                                    $('#decoderinterchangecodeid-label').hide();
                                    $('#modeminterchangecodeid-element').show();
                                    $('#modeminterchangecodeid-label').show();
                                    $('[name^=demagecodeid]').first().parents('span.form-group').hide();
                                    $('[name^=demagecodeid]').first().parents('span.form-group').prev().hide();
                                    $('[name^=catalogid]').first().parents('span.form-group').prev().hide();
                                    break;
                            }
                            break;
                        case 'HZ1':
                        case 'PAY':
                            switch (tmp[1]) {
                                case 'WKW':
                                case 'WKX':
                                    //if (['WCH'].indexOf('<?php echo $this->service->complaintcode; ?>') != false) {
                                    //    $('#modeminterchangecodeid-element').hide();
                                    //    $('#modeminterchangecodeid-label').hide();
                                    //} else if (['STB'].indexOf('<?php echo $this->service->complaintcode; ?>') != false) {
                                    //    $('#decoderinterchangecodeid-element').hide();
                                    //    $('#decoderinterchangecodeid-label').hide();
                                    //}
                                    $('#decoderinterchangecodeid-element').show();
                                    $('#decoderinterchangecodeid-label').show();
                                    $('#modeminterchangecodeid-element').show();
                                    $('#modeminterchangecodeid-label').show();
                                    $('[name^=demagecodeid]').first().parents('span.form-group').hide();
                                    $('[name^=demagecodeid]').first().parents('span.form-group').prev().hide();
                                    $('[name^=catalogid]').first().parents('span.form-group').prev().hide();
                                    break;
                            }
                            break;
                    }
                }
                return false;
            });
            function onModemCodeChange() {
                if ($("#modeminterchangecodeid-element").is(':visible') && $("#modeminterchangecodeid").val()) {
                    if ($("#modeminterchangecodeid").val()) {
                        $('[name^=demagecodeid]').first().val($("#modeminterchangecodeid").val()).trigger("chosen:updated");
                    } else {
                        $('[name^=demagecodeid]').first().val(0).trigger("chosen:updated");
                    }
                }
            };
            function onDecoderCodeChange() {
                if ($("#decoderinterchangecodeid-element").is(':visible') && $("#decoderinterchangecodeid").val()) {
                    if ($("#decoderinterchangecodeid").val()) {
                        $('[name^=demagecodeid]').first().val($("#decoderinterchangecodeid").val()).trigger("chosen:updated");
                    } else {
                        $('[name^=demagecodeid]').first().val(0).trigger("chosen:updated");
                    }
                }
            };
            $("#solutioncodeid,#performed,#decoderinterchangecodeid,#modeminterchangecodeid").on("change", function(e) {
                $('[name^=demagecodeid]').first().val(0).trigger("chosen:updated");
                onModemCodeChange();
                onDecoderCodeChange();
            });
            /*setTimeout(function() {
                $('[name^=demagecodeid]').each(function(index, element) {
                    $(element).val($(element).find('option[selected=selected]').attr('value'));
                    $(element).trigger("chosen:updated");
                });
            }, 100);*/
            //$('[name^=demagecodeid]').first().val(0).trigger("chosen:updated");
            //onModemCodeChange();
            //onDecoderCodeChange();

<?php elseif ($this->request['typeid'] == $this->types->find('installation', 'acronym')->id): ?>
            /*$("#datefinished").datetimepicker({
             dateFormat: "yy-mm-dd",
             timeFormat: 'HH:mm',
             hourGrid: 4,
             minuteGrid: 10,
             stepMinute: 5
             });*/
            $("#datefinished").datepicker({
                dateFormat: "yy-mm-dd"
            });
<?php endif; ?>
        $('#errorcodeid').on('change', function(e) {
            e.preventDefault();

            return false;
        });
        $('#errorcodeid').parents('dd').hide().prev().hide();

        function setPerformed() {
            var performed = $('[name=performed]').val();

            $.each(['installationcodeid', 'installationcancelcodeid', 'cancellationcodeid', 'solutioncodeid', 'demagecodeid', 'modeminterchangecodeid', 'decoderinterchangecodeid', 'productid', 'productreturnedid', 'demaged', 'datefinished', 'quantity'], function(key, value) {
                switch (value) {
                    case 'cancellationcodeid':
                    case 'installationcancelcodeid':
                        if (performed === '0') {
                            $('[name^=' + value + ']').removeAttr('disabled').parents('dd').show();
                            $('[name^=' + value + ']').removeAttr('disabled').parents('dd').prev().show();
                        } else {
                            $('[name^=' + value + ']').attr('disabled','disabled').parents('dd').hide();
                            $('[name^=' + value + ']').attr('disabled','disabled').parents('dd').prev().hide();
                        }
                        break;
                    case 'installationcodeid':
                    case 'solutioncodeid':
                    case 'modeminterchangecodeid':
                    case 'decoderinterchangecodeid':
                        if (performed === '1') {
                            $('[name^=' + value + ']').removeAttr('disabled').parents('dd').show();
                            $('[name^=' + value + ']').removeAttr('disabled').parents('dd').prev().show();
                        } else {
                            $('[name^=' + value + ']').attr('disabled','disabled').parents('dd').hide();
                            $('[name^=' + value + ']').attr('disabled','disabled').parents('dd').prev().hide();
                        }
                        break;
                    case 'productid':
                    case 'quantity':
                    case 'productreturnedid':
                        if (performed == 1) {
                            $('[name^=' + value + ']').removeAttr('disabled').parents('div.form-group').show();
                            //$('[name^=' + value + ']').removeAttr('disabled').parents('div.form-group').prev().show();
                            $('#return-label').show();
                            $('#product-label').show();
                        } else {
                            $('[name^=' + value + ']').attr('disabled','disabled').parents('div.form-group').hide();
                            //$('[name^=' + value + ']').attr('disabled','disabled').parents('div.form-group').prev().hide();
                            $('#return-label').hide();
                            $('#product-label').hide();
                        }
                        break;
                    case 'demaged':
                    case 'demagecodeid':
                        if (performed == 1) {
                            $('[name^=' + value + ']').removeAttr('disabled').parents('dd').show();
                            $('[name^=' + value + ']').removeAttr('disabled').parents('dd').prev().show();
                        } else {
                            $('[name^=' + value + ']').attr('disabled','disabled').parents('dd').hide();
                            $('[name^=' + value + ']').attr('disabled','disabled').parents('dd').prev().hide();
                        }
                        break;
                    case 'catalogid':
                        if (performed !== '') {
                            $('[name^=' + value + ']').removeAttr('disabled').parents('dd').show();
                        } else {
                            $('[name^=' + value + ']').attr('disabled','disabled').parents('dd').hide();
                        }
                }
            });
            $.each(['datefinished', 'technicalcomments'], function(key, value) {
                if (performed !== '') {
                    $('#' + value).removeAttr('disabled').parents('dd').show();
                    $('#' + value).removeAttr('disabled').parents('dd').prev().show();
                    $('#submit').parents('dd').show();
                    $('#cancel').show();
                } else {
                    $('#' + value).attr('disabled','disabled').parents('dd').hide();
                    $('#' + value).attr('disabled','disabled').parents('dd').prev().hide();
                    $('#submit').parents('dd').hide();
                    $('#cancel').hide();
                }
            });
        }
        ;

        $('[name=performed]').on('change', function() {
            setPerformed();
        });
        setPerformed();
        $('#solutioncodeid').trigger('change');
    });
</script>