<h2 class="sub-header">
    <?php if ($this->service): ?>
        <?php if ($this->request['typeid'] == $this->types->find('installation', 'acronym')->id): ?>
            Instalacja
        <?php elseif ($this->request['typeid'] == $this->types->find('service', 'acronym')->id): ?>
            Serwis
        <?php endif; ?>
        - <?php echo $this->service->client; ?>
    <?php else: ?>
        Nowe zlecenie
    <?php endif ?>
</h2>

<?php if ($this->success): ?>
    <div class="alert alert-success"><?php echo $this->success; ?></div> 
    <button type="button" class="btn btn-success">Powrót</button>
<?php else: ?> 

    <?php if ($this->form->getDescription()): ?>
        <div class="alert alert-danger"><?php echo $this->form->getDescription(); ?></div>
    <?php endif; ?>

    <?php
    $this->form->setAction($this->url());
    echo $this->form;
    ;
    ?>

<?php endif; ?> 

<script>
    setTimeout(function() {
        $('.btn-success').trigger('click');
    }, 1000);
</script>