<h2 class="sub-header">Zmień hasło</h2>

<?php if ($this->success): ?>
    <div class="alert alert-success"><?php echo $this->success; ?></div> 
    <button type="button" class="btn btn-success">Powrót</button>
<?php else: ?> 

    <?php if ($this->form->getDescription()): ?>
        <div class="alert alert-danger"><?php echo $this->form->getDescription(); ?></div>
    <?php endif; ?>

    <?php
    $this->form->setAction($this->url());
    echo $this->form;
    ;
    ?>

<?php endif; ?> 

<script>
    $(document).ready(function() {
        var options = {};
        options.ui = {
            showPopover: true,
            showErrors: true,
            showVerdictsInsideProgressBar: true,
            errorMessages: {
                wordLength: "Hasło jest zbyt krótkie",
                wordNotEmail: "Hasło nie może zawierać adresu e-mail",
                wordSimilarToUsername: "Hasło nie może zawierać loginu",
                wordTwoCharacterClasses: "Używaj różne klasy znaków",
                wordRepetitions: "Zbyt wiele powtórzeń znaków",
                wordSequences: "Hasło zawiera sekwencje znaków"
            }
        };
        options.rules = {
            activated: {
                wordTwoCharacterClasses: true,
                wordRepetitions: true
            }
        };
        options.common = {
            onKeyUp: function(evt, data) {
                //console.log($(evt.target).val().length, data.score);
                $('[name=score]').val(data.score);
            }
        }
        $('#password').pwstrength(options);
    });
</script>