<h2 class="sub-header">Lista zwrotów</h2>

<div class="panel panel-default">
    <div class="panel-body">
        <form class="form-inline form-load" action="<?php
        echo $this->url(
                array('module' => 'warehouse', 'controller' => 'returns', 'action' => 'list'), 'default', true)
        ?>">
            <div class="form-group">
                <select class="form-control chosen-select" name="statusid[]" multiple data-placeholder="Wybierz status">
                    <option value="">Wybierz status</option>
                    <?php foreach ($this->statuses as $status): if ($status['acronym'] == 'deleted'): continue; endif; ?>
                        <option value="<?php echo $status->id; ?>" <?php if (!empty($this->request['statusid']) && in_array($status->id, (array)$this->request['statusid'])): ?>selected<?php endif; ?>><?php echo $status->name; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <select class="form-control chosen-select" name="technicianid[]" multiple data-placeholder="Wybierz technika">
                    <option value="">Wybierz technika</option>
                    <?php foreach ($this->technicians as $technician): ?>
                        <option value="<?php echo $technician->id; ?>" <?php if (!empty($this->request['technicianid']) && in_array($technician->id, (array) $this->request['technicianid'])): ?>selected<?php endif; ?>><?php echo $technician->lastname . ' ' . $technician->firstname; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <!--<input type="text" class="form-control" name="name" placeholder="Nazwa" value="<?php if (!empty($this->request['name'])) echo $this->request['name']; ?>">-->
                <textarea class="form-control" name="name" placeholder="SN"><?php if (!empty($this->request['name'])): $names = preg_split("/[\s,]+/", $this->request['name']); echo join(",\r\n", $names); endif; ?></textarea>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="clientnumber" placeholder="Nr klienta" value="<?php if (!empty($this->request['clientnumber'])) echo $this->request['clientnumber']; ?>">
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="service" placeholder="Nr zlecenia" value="<?php if (!empty($this->request['service'])) echo $this->request['service']; ?>">
            </div>
            <button type="button" class="btn btn-default search">Szukaj</button>
            <button type="button" class="btn btn-link xls">Zapisz XLS</button>
        </form>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover table-condensed" style="empty-cells: hide;" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th style="max-width: 15px !important;">
        <div class="checkbox">
            <label>
                <input type="checkbox" class="check-all">
            </label>
        </div>
        </th>
        <th>Nazwa</th>
        <th style="max-width: 55px !important;">Uszkodzony</th>
        <th style="max-width: 125px !important;">Data</th>
        <th style="max-width: 75px !important;">Nr zlecenia</th>
        <th style="max-width: 75px !important;">Nr klienta</th>
        <th style="max-width: 175px !important;">Adres</th>
        <?php if ($this->auth->role != 'technician'): ?>
            <th style="max-width: 155px !important;">Technik</th>
        <?php endif; ?>
        <th style="max-width: 55px !important;">Nr listu</th>
        <th style="max-width: 55px !important;">Status</th>
        <th style="max-width: 55px !important;">
            <?php if ($this->auth && $this->HasAccess($this->auth->role, 'returns', 'accept')): ?>
                <a href="<?php echo $this->baseUrl; ?>/warehouse/returns/accept" data-target=".modal-body" class="popup-load multi" title="Potwierdź zwrot">
                    <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
                </a>
            <?php endif; ?>
            <?php if ($this->auth && $this->HasAccess($this->auth->role, 'returns', 'send')): ?>
                <a href="<?php echo $this->baseUrl; ?>/warehouse/returns/send" data-target=".modal-body" class="popup-load multi" title="Wyślij do UPC">
                    <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                </a>
            <?php endif; ?>
        </th>
        </tr>
        </thead>
        <?php foreach ($this->returns as $return) : ?>
            <tr>
                <td>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="id" value="<?php echo $return->id; ?>">
                        </label>
                    </div>
                </td>
                <td><?php echo $return->name ? $this->escape($return->name) : '&nbsp;'; ?></td>
                <td><?php
                        if ($return->demaged != null): echo $return->demaged ? 'tak' : 'nie';
                        else: echo "nie";
                        endif;
                        ?></td>
                <td><?php echo $this->escape($return->dateadd); ?></td>
                <td><?php echo $this->escape($return->service); ?></td>
                <td><?php echo $this->escape($return->clientnumber); ?></td>
                <td><?php echo $this->escape($return->client); ?></td>
                <?php if ($this->auth->role != 'technician'): ?>
                    <td>
                        <?php echo $this->escape($return->getService()->getTechnician()); ?>
                        <?php if ($technician = $return->getService()->getTechnician()): ?>
                            <span class="glyphicon glyphicon-info-sign" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="<?php echo '<span>Telefon: ' . $technician->phoneno . "<br />E-mail: " . $technician->email . "<br />Kod technika: " . $technician->symbol; ?></span>"></span>
                        <?php
                        else: echo "&nbsp;";
                        endif;
                        ?>
                    </td>
                <?php endif; ?>
                <td><?php echo $this->escape($return->waybill); ?></td>
                <td><?php echo $this->escape($return->status); ?></td>
                <td>
                    <?php if ($this->auth && $return->isNew() && $this->HasAccess($this->auth->role, 'returns', 'accept')): ?>
                        <a href="<?php echo $this->baseUrl; ?>/warehouse/returns/accept/id/<?php echo $return->id; ?>" data-target=".modal-body" class="popup-load" title="Potwierdź zwrot">
                            <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
                        </a>
                    <?php endif; ?>
                    <?php if ($this->auth && $return->isConfirmed() && $this->HasAccess($this->auth->role, 'returns', 'send')): ?>
                        <a href="<?php echo $this->baseUrl; ?>/warehouse/returns/send/id/<?php echo $return->id; ?>" data-target=".modal-body" class="popup-load" title="Wyślij do UPC">
                            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
<?php endforeach; ?> 
    </table> 
</div>
<?= $this->paginationControl($this->paginator, 'Sliding', 'helpers/pagination.phtml', array('urlParams' => $this->request)); ?>
<script>
    params = <?php echo Zend_Json::encode($this->request); ?>;
    $(document).ready(function() {
        $('[data-toggle="popover"]').popover({
            html: true
        });
        $('[data-toggle="tooltip"]').tooltip({
            html: true,
            content: function() {
                return $(this).attr('title').replace(/\[br\]/g, "<br />");
            }
        });
        $('[name=warehouseid]').outerWidth(200);
        $('.chosen-select').chosen({allow_single_deselect: true});
        columnsDef = [{
                'bSortable': false,
                'aTargets': [0]
            },
            {
                'bSortable': false,
                'aTargets': [10]
            }];
    });
</script>
<script src="/js/dataTables.js" />

<iframe id="file-download" name="file-download" style="display: none"></iframe>